FROM amazonlinux:2023.6.20250218.2
RUN dnf update -y
RUN dnf install -y findutils git gzip libicu tar
RUN { [ "$(uname -m)" = "aarch64" ] && echo arm64 || echo x64; } > /tmp/arch.txt

RUN curl -L -o /tmp/dotnet.tar.gz https://builds.dotnet.microsoft.com/dotnet/Sdk/9.0.200/dotnet-sdk-9.0.200-linux-$(cat /tmp/arch.txt).tar.gz
RUN mkdir /usr/local/bin/dotnet
RUN tar -xzf /tmp/dotnet.tar.gz -C /usr/local/bin/dotnet
RUN rm /tmp/dotnet.tar.gz
ENV PATH="/usr/local/bin/dotnet:${PATH}"

RUN curl -L -o /tmp/node.tar.gz https://nodejs.org/dist/v22.14.0/node-v22.14.0-linux-$(cat /tmp/arch.txt).tar.gz
RUN mkdir /usr/local/bin/node
RUN tar -xzf /tmp/node.tar.gz --strip-components=1 -C /usr/local/bin/node
RUN rm /tmp/node.tar.gz
ENV PATH="/usr/local/bin/node/bin:${PATH}"

RUN corepack prepare pnpm@10.4.1 --activate
RUN corepack enable pnpm

RUN rm /tmp/arch.txt
CMD dotnet restore "\$(basename "\$PWD").sln" && pnpm install
